config/routes.rb
DinnerDash::Application.routes.draw do
  devise_for :users
  devise_for :admins
  authenticated :admin do
    root to: "dashboards#show", as: :authenticated_root
  end

  root 'products#index'
  resources :products, except: [:destroy] do
    get 'retired', on: :collection
  end

  resources :categories, only: [:new, :create, :show, :edit, :update]
  resources :line_items, only: [:create, :update, :destroy]
  get 'cart', to: "cart#show"
  resources :transactions, only: [:new, :create]
  resource :dashboard, only: [:show]

  resources :orders, only: [:edit, :update] do
    patch 'cancel', on: :member
    patch 'paid', on: :member
    patch 'complete', on: :member
  end

  resources :users do
    resources :orders, only: [:index, :show]
  end
end

app/views/shared/_cart_link.html.erb
<% unless admin_signed_in? %>
<li>
<%= link_to "View Cart (#{pluralize(current_cart.count, "Item")}) $#{current_cart.total_price}",
     cart_path, class: "cart-link" %>
</li>
<% end %>

app/views/shared/_header_links.html.erb
<div id='header-links'>
  <ul>
    <li> <%= link_to "Home", root_path %></li>
    <%= render 'shared/user_menu' %>
    <div id="cart-link">
      <%= render "shared/cart_link" %>
    </div>
    <div id='auth-links' >
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </div>
  </ul>
</div>

app/views/shared/_user_menu.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to 'Order History', user_orders_path(current_user), id: "orders-link" %>
  </li>
<% end %>