config/routes.rb
DinnerDash::Application.routes.draw do
  devise_for :users
  devise_for :admins
  authenticated :admin do
    root to: "dashboards#show", as: :authenticated_root
  end

  root 'products#index'
  resources :products, except: [:destroy] do
    get 'retired', on: :collection
  end

  resources :categories, only: [:new, :create, :show, :edit, :update]
  resources :line_items, only: [:create, :update, :destroy]
  get 'cart', to: "cart#show"
  resources :transactions, only: [:new, :create]
  resource :dashboard, only: [:show]

  resources :orders, only: [:edit, :update] do
    patch 'cancel', on: :member
    patch 'paid', on: :member
    patch 'complete', on: :member
  end

  resources :users do
    resources :orders, only: [:index, :show]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_admin!

  def show
    @dashboard = AdminDashboard.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_admin!

  def show
    @dashboard = AdminDashboard.new(filter_orders_params)
  end

  private

  def filter_orders_params
    params.permit(:orders_page, :order_status, :search_by_user_query)
  end
end

app/views/dashboards/_product_links.html.erb
<li class='product'>
  <%= link_to product.title.titleize, product_path(product) %>
  <% if admin_signed_in? %>
    <%= link_to "Edit", edit_product_path(product), 
      id: "edit_product_#{product.id}_link" %>
  <% end %>
</li>

app/views/dashboards/show.html.erb
<h1 id="admin-dashboard-title" class='center'>Admin Dashboard</h1>

<h3>Recent Orders</h3>
<h5>Filter by Status:
  <%= link_to_unless(@dashboard.orders_filtered_by == :ordered, 
                     "Ordered", dashboard_path(order_status: :ordered)) %>
  <%= link_to_unless(@dashboard.orders_filtered_by == :paid, 
                     "Paid", dashboard_path(order_status: :paid)) %>
  <%= link_to_unless(@dashboard.orders_filtered_by == :canceled,
                     "Canceled", dashboard_path(order_status: :canceled)) %>
  <%= link_to_unless(@dashboard.orders_filtered_by == :complete, 
                     "Completed", dashboard_path(order_status: :complete)) %>
  <% if @dashboard.has_order_filter? %>
    <%= link_to "Clear filter", dashboard_path, class: "clear-order-filter" %>
  <% end %>
</h5>
<%= render partial: 'orders/search_form', locals: { path: dashboard_path } %>
<div class="dashboard-orders">
  <ul>
    <%= render partial: 'orders/edit_order_link',
      collection: @dashboard.orders, as: :order %>
    <%= will_paginate @dashboard.orders, param_name: :orders_page %>
  </ul>
</div>

<% cache(cache_key_for_categories) do %>
  <div class="categories">
    <h3>Menu Categories</h3>
    <ul>
      <%= render @dashboard.categories %>
    </ul>
  </div>
<% end %>

<% cache(cache_key_for_products) do %>
  <div class="products">
    <h3>Menu Items</h3>

    <ul>
      <%= render partial: 'product_links',
        collection: @dashboard.products, as: :product %>
    </ul>
    <%= link_to "View Retired Items", retired_products_path,
      id: "retired-products-link" %>
  </div>
<% end %>

<%= link_to "Create New Menu Item", new_product_path, id: 'new-product-link'%>
<%= link_to "Create New Menu Category", new_category_path, id: 'new-category-link'%>