config/routes.rb
DinnerDash::Application.routes.draw do
  devise_for :users
  devise_for :admins
  authenticated :admin do
    root to: "dashboards#show", as: :authenticated_root
  end

  root 'products#index'
  resources :products, except: [:destroy] do
    get 'retired', on: :collection
  end

  resources :categories, only: [:new, :create, :show, :edit, :update]
  resources :line_items, only: [:create, :update, :destroy]
  get 'cart', to: "cart#show"
  resources :transactions, only: [:new, :create]
  resource :dashboard, only: [:show]

  resources :orders, only: [:edit, :update] do
    patch 'cancel', on: :member
    patch 'paid', on: :member
    patch 'complete', on: :member
  end

  resources :users do
    resources :orders, only: [:index, :show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_products
  has_many :products, through: :category_products
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_admin!, except: [:show]

  def show
    @presenter = ProductsPresenter.for(category_id, current_cart)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.products << Product.where(id: product_ids)

    if @category.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(category_id)
  end

  def update
    @category = Category.find(category_id)

    if @category.update(category_params)
      @category.products = Product.where(id: product_ids)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def category_id
    params[:id]
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def product_ids
    params[:category][:product_ids]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def cache_key_for_categories
    "categories/all-#{count}-#{max_updated_at}"
  end

  private

  def count
    Category.count
  end

  def max_updated_at
    Category.maximum(:updated_at).try(:utc).try(:to_s, :number)
  end
end

app/views/categories/_category.html.erb
<li class='category'>
  <%= link_to category.name.titleize, category_path(category) %>
  <% if admin_signed_in? %>
    <%= link_to "Edit", edit_category_path(category),
      id: "edit_category_#{category.id}_link" %>
  <% end %>
</li>

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.association :products, as: :check_boxes %>
  <%= f.submit "Submit", id: "category-submit-button", class: "button" %>
<% end %>

app/views/categories/edit.html.erb
<h2 id="edit-category-title">Edit Menu Category</h2>
<%= render partial: 'form' %>

app/views/categories/new.html.erb
<h2 id="create-menu-item-title">Create Menu Category</h2>
<%= render partial: 'form' %>

app/views/categories/show.html.erb
<% cache(cache_key_for_categories) do %>
  <div id="category-links" class="col-sm-3 col-md-2 sidebar">
    <ul>
      <%= render @presenter.categories %>
    </ul>
  </div>
<% end %>

<% cache(cache_key_for_products) do %>
  <ul>
    <%= render 'products/tiles', products: @presenter.products %>
  </ul>
<% end %>

app/views/categories/show.js.erb
$( '#cart-link' ).html("<%= escape_javascript(render('shared/cart_link')) %>");